import type { ImportEntityType } from '@/types/import'

export const IMPORT_TARGET_FIELDS: Record<ImportEntityType, string[]> = {
  companies: [
    'name',
    'legal_name',
    'website',
    'email',
    'phone',
    'address_line1',
    'city',
    'province',
    'postal_code',
    'country',
    'industry',
    'status',
    'source',
    'notes_summary',
  ],
  contacts: [
    'first_name',
    'last_name',
    'role',
    'email',
    'phone',
    'mobile_phone',
    'whatsapp',
    'company_name',
    'status',
    'notes_summary',
  ],
  opportunities: [
    'title',
    'company_name',
    'primary_contact_name',
    'stage',
    'value_estimate',
    'probability',
    'expected_close_date',
    'next_action',
    'notes',
  ],
  followups: [
    'title',
    'company_name',
    'contact_name',
    'due_at',
    'priority',
    'status',
    'description',
  ],
  unknown: [],
}
